[options]
admin_passwd = Vieira
db_host = 127.0.0.1
db_port = 5432
db_user = odoo18
db_password = admin
http_port = 8090
limit_time_real = 2400
server_wide_modules = web
addons_path = /home/fvieira/workspace/odoo18/odoo/addons,/home/fvieira/workspace/odoo18/AllToPack
data_dir = /home/fvieira/.local/share/Odoo18
log_level = info
